### ISSUE TITLE
Idea: Trigger run on webhook activity

### ISSUE THREAD

**Issue by billimek** [vito/tracksuit#9]
@vito what do you think about this idea?

Instead of running tracksuit manually or on some sort of periodic schedule, why not:

Extend tracksuit to have the ability to listen for 'webhook' activity from either Tracker or Github and trigger an execution whenever an event is received?

In other words:
* Configure Pivotal Tracker project(s) to have an 'Activity Webhook' pointing to the tracksuit 'server' endpoint
* Configure Githuib Repo(s) to have new webhook triggered on 'issues' activities pointing to the tracksuit 'server' endpoint

Initially this could just execute whenever any request comes through, and then perhaps add features to
* parse incoming tracker webhook POST to collect the tracker project ID
* parse incoming github webhook POST to collect the github repo name and github org name

**Comment by vito** [comment]
It'd be nice to not require polling but this probably won't be happening. I wrote tracksuit this way because I got tired of having to configure webhooks all over the place. I'd rather just spin up a while loop somewhere than deploy a server and click around.
